name: Go CI

on:
  push:
    branches:
      - main

jobs:
  go-ci:
      runs-on: ubuntu-latest

      steps:
        - name: Check out main repository
          uses: actions/checkout@v4

        - name: Check additional repo
          uses: actions/checkout@v4
          with:
            repository: 'test-diplomski/magnetar'
            path: 'magnetar'

        - name: Move magnetar to parent directory
          run: mv magnetar ../magnetar
          
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.22.3'

        - name: Update and tidy Go modules for health-check
          run: go mod tidy
          working-directory: ./health-check 
    
        - name: Install dependencies for health-check
          run: go mod download
          working-directory: ./health-check

        - name: Build health-check
          run: go build -v ./...
          working-directory: ./health-check

        - name: Update and tidy Go modules for node-metrics
          run: go mod tidy
          working-directory: ./node-metrics
    
        - name: Install dependencies for node-metrics
          run: go mod download
          working-directory: ./node-metrics

        - name: Build node-metrics
          run: go build -v ./...
          working-directory: ./node-metrics
  # docker:
  #   runs-on: ubuntu-latest
  #   needs: go-ci
  #   if: github.repository == 'test-diplomski/protostar'

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/protostar:latest
